% Generated by MATLAB(R) 9.10 (R2021a) and LTE Toolbox 3.5 (R2021a).
% Generated on: 07-Jul-2024 15:33:25

%% Generate Downlink RMC Waveform
% Downlink RMC configuration:
cfg = struct('RC', 'R.0', ...
    'DuplexMode', 'FDD', ...
    'NCellID', 0, ...
    'TotSubframes', 10, ...
    'NumCodewords', 1, ...
    'Windowing', 0, ...
    'AntennaPort', 1);

cfg.OCNGPDSCHEnable = 'Off';
cfg.OCNGPDCCHEnable = 'Off';
cfg.PDSCH.TxScheme = 'Port0';
cfg.PDSCH.RNTI = 1;
cfg.PDSCH.Rho = 0;
cfg.PDSCH.RVSeq = [0 1 2 3];
cfg.PDSCH.NHARQProcesses = 8;
cfg.PDSCH.PMISet = 1;
cfg = lteRMCDL(cfg);

% input bit source:
in = [1; 0; 0; 1];


% waveform generation:
[waveform, grid, cfg] = lteRMCDLTool(cfg, in);

Fs = cfg.SamplingRate; 								 % sample rate of waveform

%% Visualize Downlink RMC Waveform
% Spectrum Analyzer
spectrum = dsp.SpectrumAnalyzer('SampleRate', Fs);
spectrum(waveform);
release(spectrum);


